apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
  namespace: skywalking
  labels:
    service: skywalking-ui
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30808
    name: skywalking-ui
  type: NodePort
  selector:
    app: skywalking-ui
