apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: skywalking
  labels: 
    app: app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
        - name: skywalking-agent1
          image: zhxl1989/skywalking-agent:1.0
          imagePullPolicy: Always
          workingDir: /
          command: ["sh"]
          args:
            [
              "-c",
              "mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent",
            ]
          volumeMounts:
            - name: skywalking-agent
              mountPath: /skywalking/agent
      containers:
        - name: app
          image: zhxl1989/app:1.0
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/usr/skywalking/agent/skywalking-agent.jar
            - name: SW_AGENT_NAME
              value: app
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-oap.skywalking.svc.cluster.local:11800
            - name: SERVER_PORT
              value: "9999"
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "1Gi"
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
          volumeMounts:
            - name: date
              mountPath: /etc/localtime
            - name: skywalking-agent
              #挂载的目录
              mountPath: /usr/skywalking/agent
      volumes:
        - name: date
          hostPath:
            path: /etc/localtime
        - name: skywalking-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: skywalking
  labels:
    app: app
spec:
  sessionAffinity: "ClientIP"
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
      nodePort: 30888
  selector:
    app: app
  type: NodePort
