apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-starter-reference
  namespace: skywalking
  labels: 
    app: dubbo-starter-reference
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-starter-reference
  template:
    metadata:
      labels:
        app: dubbo-starter-reference
    spec:
      initContainers:
        - name: skywalking-agent-reference
          image: zhxl1989/skywalking-agent:1.0
          imagePullPolicy: Always
          workingDir: /
          command: ["sh"]
          args:
            [
              "-c",
              "mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent",
            ]
          volumeMounts:
            - name: skywalking-agent
              mountPath: /skywalking/agent
      containers:
        - name: dubbo-reference
          image: zhxl1989/dubbo-starter-reference:0.0.1
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/usr/skywalking/agent/skywalking-agent.jar
            - name: SW_AGENT_NAME
              value: dubbo-reference
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-oap.skywalking.svc.cluster.local:11800
            - name: SERVER_PORT
              value: "9997"
          resources:
            limits:
              memory: 2000Mi
            requests:
              memory: 1000Mi
          ports:
            - name: http
              containerPort: 9997
            - name: dubbo
              containerPort: 20881
              protocol: TCP
          volumeMounts:
            - name: date
              mountPath: /etc/localtime
            - name: skywalking-agent
              mountPath: /usr/skywalking/agent
      volumes:
        - name: date
          hostPath:
            path: /etc/localtime
        - name: skywalking-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dubbo-starter-reference
  namespace: skywalking
  labels:
    app: dubbo-starter-reference
spec:
  sessionAffinity: "ClientIP"
  ports:
    - port: 9997
      name: server
      targetPort: 9997
    - port: 20881
      name: dubbo
      targetPort: 20881
  selector:
    app: dubbo-starter-reference
  type: ClusterIP
