apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-oap
  namespace: skywalking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-oap
  template:
    metadata:
      labels:
        app: skywalking-oap
        release: skywalking
    spec:
      serviceAccountName: skywalking-oap
      containers:
      - name: skywalking-oap
        image: apache/skywalking-oap-server:8.5.0-es7
        imagePullPolicy: Always
        ports:
        - containerPort: 11800
          name: grpc
        - containerPort: 12800
          name: rest
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            cpu: 1000m
            memory: 2Gi
        env:
        - name: SW_CLUSTER
          value: "nacos"
        - name: SW_CLUSTER_NACOS_HOST_PORT
          value: "nacos-0.nacos-headless.default.svc.cluster.local:8848"
        - name: SW_CLUSTER_NACOS_USERNAME
          value: "nacos"
        - name: SW_CLUSTER_NACOS_PASSWORD
          value: "nacos"
        - name: SW_STORAGE
          value: "elasticsearch7"
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: "es7-cluster-0.elasticsearch7.default.svc.cluster.local:9200"
        - name: real_host
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /etc/localtime
          name: volume-localtime
        - name: config
          mountPath: /skywalking/ext-config/application.yml
          subPath: path/to/application.yml
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
        - name: config
          configMap:
            name: oap-config
            items:
            - key: application.yml
              path: path/to/application.yml
